### PR TITLE
Add ability to search

### PR DESCRIPTION
**Pull request by UnwrittenFun**

### CODE REVIEW

**Comment by connor4312** [comment]
These are two parameters we use on only one endpoint. It might make more sense to query manually in that case.

**Comment by SimonSchick** [comment]
Yea, was going to say, these are very specific and probably shouldn't go into in the main adapter logic, although it might be good to have this logic embedded into the lister and make it re-useable in the backend, shouldn't be too much work @connor4312

**Comment by UnwrittenFun** [comment]
Oh, I thought this was used on more endpoints..

How would I do it without this?

**Comment by connor4312** [comment]
I think it would make sense to provide a way to put raw AxiosRequestOptions in the IQueryOptions, which are deep-merged with the generated options. Thoughts @SimonSchick?

**Comment by SimonSchick** [comment]
I wanted to keep the adapter somewhat abstracted from HTTP/Axios, not sure if exposing the low level stuff is a good thing to do.

I'd prefer adding specific functionality to the adapter (and marking it as such) rather than exposing low level functions.

**Pull request closed without merging**
