### PR TITLE
Mark synced when model created with data

### PR DESCRIPTION
**Pull request by UnwrittenFun**
This fixes a bug where liveloading appeared not to be working because it thought all the properties were dirty.

This was on popout chat and i _think_, from a brief look through the code, it was only happening there because the channel is only queried for once, meaning it never hit [this line](https://github.com/WatchBeam/bORM/blob/hotfix/new-model-synced/src/ModelStore.ts#L64).

### CODE REVIEW

**Comment by SimonSchick** [comment]
I think you'll need to fix lodash typings as on frontend.

**Comment by UnwrittenFun** [comment]
Hmm, tests seem to suggest it is intended to not sync on a new model with data. What do you suggest @SimonSchick ?

**Comment by SimonSchick** [comment]
Maybe it would make more sense to mark it as synced by the consumer (fe2)?

**Comment by UnwrittenFun** [comment]
The channel is being created by bORM though, via 
```ts
this.adapter.findById(Channel, channelId)
```

**Comment by UnwrittenFun** [comment]
I've moved the markSynced call to store.inject and added a test for it.

**Pull request merged**
